# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Recipe.create([
  { :title => "Ojos saltones", :body => "Agafes uns quants ulls i els serveixes amb decoració en un plat.", :ingredients => "ulls, sang", :cooktime => "2000-01-01 14:45:00", :rating => 4.333333333333333, :numVotes => 3, :created_at => "2011-11-22 14:45:41", :updated_at => "2011-11-24 00:03:20", :zombie_id => 2, :imatge => "http://usafeast.com/images/halloween/halloween-recipes-27.jpg" },
  { :title => "Brainz en escabeche con pasas!", :body => "Agafes els brainz, fas una escabechina i despres li fiques unes pases.", :ingredients => "brainz, escabeche, destral, pases", :cooktime => "2000-01-01 01:10:00", :rating => 3.0, :numVotes => 1, :created_at => "2011-11-19 11:31:13", :updated_at => "2011-11-23 14:49:14", :zombie_id => 3, :imatge => "http://t2.gstatic.com/images?q=tbn:ANd9GcRERkvuRJscFvaPzyDdzEHTvQj26yoEILveY5xd5uVSOi0fCubHykzHEeBF" },
  { :title => "Brainz al vapor", :body => "Agafar els brainz i ficarlos al vapor", :ingredients => "brainz, aigua", :cooktime => "2000-01-01 00:20:00", :rating => 3.0, :numVotes => 2, :created_at => "2011-11-19 00:04:18", :updated_at => "2011-11-23 14:49:46", :zombie_id => 1, :imatge => nil }
])



Zombie.create([
  { :name => "Arol", :avatar => "", :bio => "He mort", :death => "2011-11-18", :created_at => "2011-11-18 00:03:36", :updated_at => "2011-11-22 12:58:56", :mail => "arolet@gmail.com" },
  { :name => "David", :avatar => "http://a2.twimg.com/profile_images/1560812305/image.jpg", :bio => "Ha mort", :death => "2011-11-11", :created_at => "2011-11-18 00:04:52", :updated_at => "2011-11-22 14:45:59", :mail => "david.cortes.18@gmail.com" },
  { :name => "Olga", :avatar => "http://www.vectorstock.com/i/composite/54,15/585415/little-zombie-girl-vector.jpg", :bio => "Nyam!", :death => "2008-12-31", :created_at => "2011-11-19 11:28:53", :updated_at => "2011-11-22 20:13:58", :mail => "" },
  { :name => "Laura", :avatar => "nil", :bio => "ñaaaa", :death => "2011-04-20", :created_at => "2011-11-20 19:00:44", :updated_at => "2011-11-20 19:00:53", :mail => nil }
])


