# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Recipe.create([
  { :title => nil, :body => nil, :ingredients => nil, :cooktime => nil, :rating => nil, :numVotes => nil, :created_at => nil, :updated_at => nil }
])



Zombie.create([
  { :name => "Arol", :avatar => "", :bio => "He mort", :death => "2011-11-18", :created_at => "2011-11-18 00:03:36", :updated_at => "2011-11-18 00:03:36" },
  { :name => "David", :avatar => "http://a2.twimg.com/profile_images/1560812305/image.jpg", :bio => "Ha mort", :death => "2011-11-11", :created_at => "2011-11-18 00:04:52", :updated_at => "2011-11-18 00:04:52" }
])


